name: Build and deploy SPA to GH Pages - cowsAndBUlls

on:
  push:
    branches:
      - main
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build 

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: 'https://manugeorge04.github.io/cowsAndBulls/'

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: 'Deploy to GH Pages'      
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build      
